/**
 * DEAD SIGNAL — Static Voice Net Registry
 * Canonical definitions for all built-in voice nets.
 * Each entry is a complete VoiceNet object (see models.js).
 */

/** @type {import('./models').VoiceNet[]} */
export const VOICE_NETS = [
  {
    id: 'net-command',
    slug: 'command',
    displayName: 'Command Net',
    frequencyLabel: '146.520 MHz',
    memorySlot: 'M1',
    category: 'command',
    type: 'net',
    priority: 2,
    disciplineMode: 'ptt',
    allowPTT: true,
    allowOpenMic: false,
    allowWhisper: true,
    spatialEnabled: false,
    roleRestrictions: [],
    bridgeable: true,
    hidden: false,
    associatedMissionId: null,
    associatedSquadId: null,
    associatedClanId: null,
    livekitRoomName: 'net-command',
    radioProfile: 'encrypted',
    scanEligible: true,
    squelchRecommended: 0.15,
    netControlEnabled: true,
    emergencyCapable: true,
  },
  {
    id: 'net-squad-alpha',
    slug: 'squad-alpha',
    displayName: 'Squad Alpha',
    frequencyLabel: '462.5625 MHz',
    memorySlot: 'M2',
    category: 'squad',
    type: 'net',
    priority: 3,
    disciplineMode: 'ptt',
    allowPTT: true,
    allowOpenMic: false,
    allowWhisper: true,
    spatialEnabled: false,
    roleRestrictions: [],
    bridgeable: true,
    hidden: false,
    associatedMissionId: null,
    associatedSquadId: null,
    associatedClanId: null,
    livekitRoomName: 'net-squad-alpha',
    radioProfile: 'analog',
    scanEligible: true,
    squelchRecommended: 0.1,
    netControlEnabled: false,
    emergencyCapable: false,
  },
  {
    id: 'net-squad-bravo',
    slug: 'squad-bravo',
    displayName: 'Squad Bravo',
    frequencyLabel: '467.5625 MHz',
    memorySlot: 'M3',
    category: 'squad',
    type: 'net',
    priority: 3,
    disciplineMode: 'ptt',
    allowPTT: true,
    allowOpenMic: false,
    allowWhisper: true,
    spatialEnabled: false,
    roleRestrictions: [],
    bridgeable: true,
    hidden: false,
    associatedMissionId: null,
    associatedSquadId: null,
    associatedClanId: null,
    livekitRoomName: 'net-squad-bravo',
    radioProfile: 'analog',
    scanEligible: true,
    squelchRecommended: 0.1,
    netControlEnabled: false,
    emergencyCapable: false,
  },
  {
    id: 'net-logistics',
    slug: 'logistics',
    displayName: 'Logistics',
    frequencyLabel: '151.940 MHz',
    memorySlot: 'M4',
    category: 'logistics',
    type: 'net',
    priority: 4,
    disciplineMode: 'open',
    allowPTT: true,
    allowOpenMic: true,
    allowWhisper: true,
    spatialEnabled: false,
    roleRestrictions: [],
    bridgeable: true,
    hidden: false,
    associatedMissionId: null,
    associatedSquadId: null,
    associatedClanId: null,
    livekitRoomName: 'net-logistics',
    radioProfile: 'clean',
    scanEligible: true,
    squelchRecommended: 0.05,
    netControlEnabled: false,
    emergencyCapable: false,
  },
  {
    id: 'net-emergency',
    slug: 'emergency',
    displayName: 'Emergency',
    frequencyLabel: '155.340 MHz',
    memorySlot: 'M5',
    category: 'emergency',
    type: 'net',
    priority: 1,
    disciplineMode: 'ptt',
    allowPTT: true,
    allowOpenMic: false,
    allowWhisper: false,
    spatialEnabled: false,
    roleRestrictions: [],
    bridgeable: false,
    hidden: false,
    associatedMissionId: null,
    associatedSquadId: null,
    associatedClanId: null,
    livekitRoomName: 'net-emergency',
    radioProfile: 'encrypted',
    scanEligible: true,
    squelchRecommended: 0.0,
    netControlEnabled: true,
    emergencyCapable: true,
  },
  {
    id: 'net-proximity',
    slug: 'proximity',
    displayName: 'Proximity',
    frequencyLabel: 'LOCAL',
    memorySlot: 'M6',
    category: 'proximity',
    type: 'spatial',
    priority: 6,
    disciplineMode: 'open',
    allowPTT: false,
    allowOpenMic: true,
    allowWhisper: false,
    spatialEnabled: true,
    roleRestrictions: [],
    bridgeable: false,
    hidden: false,
    associatedMissionId: null,
    associatedSquadId: null,
    associatedClanId: null,
    livekitRoomName: 'net-proximity',
    radioProfile: 'natural',
    scanEligible: false,
    squelchRecommended: null,
    netControlEnabled: false,
    emergencyCapable: false,
  },
];

/** Quick lookup map by net id */
export const VOICE_NETS_BY_ID = Object.fromEntries(VOICE_NETS.map(n => [n.id, n]));

/** Quick lookup map by livekit room name */
export const VOICE_NETS_BY_ROOM = Object.fromEntries(VOICE_NETS.map(n => [n.livekitRoomName, n]));

/** Quick lookup map by memory slot */
export const VOICE_NETS_BY_SLOT = Object.fromEntries(VOICE_NETS.map(n => [n.memorySlot, n]));
