export interface RuntimeConfigRecord {
  version: string;
  config: Record<string, unknown>;
  updated_at: string;
  source: "live";
}

export const RUNTIME_CONFIG_KEY = "global";

export const DEFAULT_RUNTIME_CONFIG: Record<string, unknown> = {
  app: {
    title: "DEAD SIGNAL",
    build: "DS-ALPHA",
    version: "v1.0.0",
    timezone: "America/Vancouver",
    launch: {
      enabled: true,
      label: "DEPLOY",
      game_url: "",
      server_url: "",
      open_server_delay_ms: 2500,
      tooltip: "Set app.launch.game_url/server_url (or gameUrl/serverUrl). Optional env fallback: VITE_DEAD_SIGNAL_GAME_URL / VITE_DEAD_SIGNAL_SERVER_URL.",
    },
    voice: {
      enabled: true,
      token_function: "livekitToken",
      default_ops_room: "operations-oncall",
      default_clan_room: "clan-primary",
      mission_room_prefix: "mission-",
      whisper_suffix: "-whisper-",
      tooltip: "Voice uses VITE_LIVEKIT_URL client config and server-side LIVEKIT_API_KEY/LIVEKIT_SECRET signing.",
    },
  },
  world: {
    server_timezone: "America/Vancouver",
    time_scale: 6,
    anchor_real_iso: "2026-01-01T00:00:00Z",
    anchor_game_iso: "2234-03-01T06:00:00Z",
    day_zero_game_iso: "2234-01-01T00:00:00Z",
    conditions_location: {
      latitude: 49.2827,
      longitude: -123.1207,
    },
    seasons: [
      {
        name: "Winter",
        start_month: 12,
        end_month: 2,
        color: "#00e8ff",
        impacts: [
          "Body temperature drain +24%",
          "Hydration loss -10%",
          "Night visibility +8% on clear skies",
        ],
      },
      {
        name: "Spring",
        start_month: 3,
        end_month: 5,
        color: "#39ff14",
        impacts: [
          "Crop yield +18%",
          "Ambient infection spread +7%",
          "Road traction baseline",
        ],
      },
      {
        name: "Summer",
        start_month: 6,
        end_month: 8,
        color: "#ffaa00",
        impacts: [
          "Hydration drain +26%",
          "Heat fatigue threshold -14%",
          "Solar array output +22%",
        ],
      },
      {
        name: "Autumn",
        start_month: 9,
        end_month: 11,
        color: "#ff6a00",
        impacts: [
          "Foraging yield +12%",
          "Fog event probability +18%",
          "Daylight window -21 minutes/day",
        ],
      },
    ],
  },
  navigation: {
    sections: [
      {
        label: "// OPS CENTER",
        items: [
          { label: "COMMAND", page: "Dashboard", code: "HQ", color: "#ffb000", dot: "#39ff14", icon: "Terminal" },
          { label: "SERVER", page: "ServerMonitor", code: "SRV", color: "#00e5ff", dot: "#00e5ff", icon: "Cpu" },
        ],
      },
      {
        label: "// FIELD OPS",
        items: [
          { label: "TACTICAL MAP", page: "TacticalMap", code: "MAP", color: "#ffb000", dot: "#ffb000", icon: "Map" },
          { label: "CLAN ROSTER", page: "ClanRoster", code: "OPS", color: "#b8a890", dot: "#39ff14", icon: "Users" },
          { label: "MISSIONS", page: "Missions", code: "MIS", color: "#ff2020", dot: "#ff2020", icon: "Crosshair" },
        ],
      },
      {
        label: "// LOGISTICS",
        items: [
          { label: "INVENTORY", page: "Inventory", code: "INV", color: "#b8a890", dot: "#8a7a6a", icon: "Package" },
          { label: "ENGINEERING", page: "EngineeringOps", code: "ENG", color: "#00e5ff", dot: "#00e5ff", icon: "Wrench" },
          { label: "INTEL FEED", page: "Intel", code: "INT", color: "#ffb000", dot: "#ffb000", icon: "Radio" },
          { label: "AI AGENT", page: "AIAgent", code: "AI", color: "#39ff14", dot: "#39ff14", icon: "Bot" },
        ],
      },
    ],
  },
  terminal: {
    pages: [
      { cmd: "goto dashboard", label: "COMMAND HQ", page: "Dashboard" },
      { cmd: "goto server", label: "SERVER MONITOR", page: "ServerMonitor" },
      { cmd: "goto map", label: "TACTICAL MAP", page: "TacticalMap" },
      { cmd: "goto roster", label: "CLAN ROSTER", page: "ClanRoster" },
      { cmd: "goto missions", label: "MISSIONS", page: "Missions" },
      { cmd: "goto inventory", label: "INVENTORY", page: "Inventory" },
      { cmd: "goto engineering", label: "ENGINEERING OPS", page: "EngineeringOps" },
      { cmd: "goto intel", label: "INTEL FEED", page: "Intel" },
      { cmd: "goto ai", label: "AI AGENT", page: "AIAgent" },
      { cmd: "goto stats", label: "MY STATS", page: "MyStats" },
      { cmd: "goto loot", label: "LOOT TRACKER", page: "LootTracker" },
      { cmd: "goto loadout", label: "LOADOUT PLANNER", page: "LoadoutPlanner" },
      { cmd: "goto deaths", label: "DEATH MAP", page: "DeathMap" },
      { cmd: "goto treasury", label: "CLAN TREASURY", page: "ClanTreasury" },
      { cmd: "goto wiki", label: "CLAN WIKI", page: "ClanWiki" },
      { cmd: "goto calendar", label: "CLAN CALENDAR", page: "ClanCalendar" },
      { cmd: "goto vote", label: "CLAN VOTING", page: "ClanVoting" },
      { cmd: "goto challenges", label: "CHALLENGES", page: "Challenges" },
      { cmd: "goto board", label: "CLAN BOARD", page: "ClanBoard" },
    ],
  },
  taxonomy: {
    mission_statuses: ["Pending", "Active", "Complete", "Failed", "Aborted"],
    mission_status_filters: ["All", "Pending", "Active", "Complete", "Failed", "Aborted"],
    mission_priorities: ["Critical", "High", "Medium", "Low"],
    inventory_categories: ["Weapon", "Ammo", "Medical", "Food", "Water", "Tool", "Material", "Clothing", "Misc"],
    inventory_conditions: ["Pristine", "Good", "Worn", "Damaged", "Ruined"],
    inventory_locations: ["Carried", "Stash", "Vehicle", "Base Storage"],
    challenge_categories: ["All", "Combat", "Survival", "Looting", "Social", "Exploration"],
    death_causes: ["Zombie", "Player", "Fall", "Hunger", "Thirst", "Cold", "Unknown"],
    clan_roles: ["Commander", "Lieutenant", "Scout", "Engineer", "Medic", "Grunt"],
    clan_statuses: ["Active", "Inactive", "MIA", "KIA"],
    clan_channels: ["General", "Ops", "Loot", "Tactical", "Off-Topic"],
    clan_vote_statuses: ["Open", "Closed"],
    clan_vote_filters: ["All", "Open", "Closed"],
    clan_wiki_categories: ["All", "Base Building", "Crafting", "Survival", "Weapons", "Locations", "Tactics", "Rules", "Other"],
    clan_event_types: ["All", "Raid", "Loot Run", "Base Building", "Training", "Meeting", "Social", "Other"],
    clan_event_statuses: ["Upcoming", "Completed", "Cancelled"],
    intel_types: ["Emergency", "Intel", "Ops", "General", "Maintenance"],
    loot_categories: ["All", "Weapon", "Ammo", "Medical", "Food", "Water", "Tool", "Material", "Clothing", "Misc"],
    loot_status_filters: ["All", "Open", "Fulfilled", "Cancelled"],
    loot_urgencies: ["Low", "Medium", "High", "Critical"],
    loadout_roles: ["Combat", "Scavenger", "Medic", "Scout", "Builder", "Generalist"],
    loadout_default_slots: [
      "Primary Weapon",
      "Secondary Weapon",
      "Melee",
      "Helmet",
      "Body Armor",
      "Backpack",
      "Medical Kit",
      "Food",
      "Water",
      "Ammo (Primary)",
      "Ammo (Secondary)",
      "Tools",
    ],
    map_pin_types: ["Loot Cache", "Safe House", "Danger Zone", "Resource Node", "Enemy Sighting", "Clan Base", "Vehicle Spawn", "Objective", "Horde Sighting", "Rally Point", "Route Waypoint", "Other"],
    map_horde_directions: ["N", "NE", "E", "SE", "S", "SW", "W", "NW"],
    map_pin_statuses: ["Unknown", "Fresh", "Looted", "Active", "Cleared"],
    treasury_actions: ["Deposit", "Withdrawal"],
    treasury_action_filters: ["All", "Deposit", "Withdrawal"],
  },
  alerting: {
    metrics: [
      { value: "cpu", label: "CPU Usage (%)" },
      { value: "ramUsedMB", label: "RAM Used (MB)" },
      { value: "diskMB", label: "Disk Used (MB)" },
      { value: "networkRxKB", label: "Net Download (KB/s)" },
      { value: "networkTxKB", label: "Net Upload (KB/s)" },
      { value: "responseTime", label: "Response Time (ms)" },
      { value: "playerCount", label: "Player Count" },
      { value: "serverFps", label: "Server FPS" },
      { value: "processCount", label: "Process Count" },
      { value: "activeConnections", label: "Active Connections" },
    ],
    operators: [
      { value: "gt", label: ">" },
      { value: "gte", label: ">=" },
      { value: "lt", label: "<" },
      { value: "lte", label: "<=" },
      { value: "eq", label: "=" },
      { value: "neq", label: "!=" },
    ],
  },
  ai: {
    modes: [
      { id: "wiki", label: "WIKI AGENT", icon: "BookOpen", color: "#00e5ff", desc: "Game mechanics, items, enemies" },
      { id: "crafting", label: "CRAFTING AI", icon: "Wrench", color: "#ffb000", desc: "Recipes, materials, crafting chains" },
      { id: "intel", label: "TACTICAL AI", icon: "Map", color: "#ff2020", desc: "Loot routes, tactics, survival" },
      { id: "general", label: "COMMAND AI", icon: "Zap", color: "#39ff14", desc: "Clan ops & server management" },
    ],
    quick_prompts: {
      wiki: ["Best weapons?", "How does base building work?", "What do zombies drop?", "Beginner survival tips"],
      crafting: ["Craft with wood and metal?", "How to craft a rifle?", "Best early crafts?", "Generator materials?"],
      intel: ["Best loot zones?", "Defend base from raids?", "Best PvP loadout?", "Early game strategy"],
      general: ["Manage whitelists?", "Best clan role setup?", "Track player activity?", "Server performance tips"],
    },
    system_prompts: {
      wiki: "You are DEAD SIGNAL — an AI embedded in a HumanitZ game companion terminal. Answer questions about the survival game HumanitZ: items, weapons, crafting, base building, zombies, mechanics, tips and tricks. Keep answers concise and formatted for a terminal interface. Use military/survival tone. Format with headers using // and bullet points with >.",
      crafting: "You are DEAD SIGNAL CRAFTING UNIT — an AI specialist in HumanitZ crafting systems. Help players understand crafting recipes, material requirements, crafting chains, and priority items to craft. Be specific about quantities and materials. Terminal format with // headers and > bullets.",
      intel: "You are DEAD SIGNAL TACTICAL — a survival and tactical AI for HumanitZ players. Provide advice on loot routes, base defense, PvP tactics, zombie strategies, resource management. Terminal format with // headers, > bullets, tactical tone.",
      general: "You are DEAD SIGNAL COMMAND — the AI core of a clan companion app for HumanitZ. Help with clan management, server administration, player coordination, base planning. Professional, no-nonsense terminal tone.",
    },
  },
  engineering: {
    asset_types: [
      { id: "gear", label: "Gear" },
      { id: "vehicle", label: "Vehicle" },
      { id: "building", label: "Building" },
    ],
    stat_catalog: [
      { key: "durability", label: "Durability", unit: "%" },
      { key: "defense", label: "Defense", unit: "" },
      { key: "power", label: "Power Draw", unit: "kW", lower_is_better: true },
      { key: "capacity", label: "Capacity", unit: "" },
      { key: "speed", label: "Speed", unit: "km/h" },
      { key: "weight", label: "Weight", unit: "kg", lower_is_better: true },
    ],
    modifiers: [
      {
        id: "mod-reinforced-plating",
        label: "Reinforced Plating",
        target_types: ["gear", "vehicle", "building"],
        effects: {
          durability: 15,
          defense: 8,
          weight: 4,
        },
        resource_costs: [
          { item: "Metal", quantity: 60 },
          { item: "Tool Kit", quantity: 1 },
        ],
        tech_requirements: ["tech-materials-tier2"],
      },
      {
        id: "mod-efficient-grid-controller",
        label: "Efficient Grid Controller",
        target_types: ["building"],
        effects: {
          power: -20,
          durability: 5,
        },
        resource_costs: [
          { item: "Electronics", quantity: 30 },
          { item: "Copper Wire", quantity: 40 },
        ],
        tech_requirements: ["tech-grid-optimization"],
      },
      {
        id: "mod-lightweight-chassis",
        label: "Lightweight Chassis",
        target_types: ["vehicle"],
        effects: {
          speed: 12,
          weight: -15,
          durability: -5,
        },
        resource_costs: [
          { item: "Alloy Plate", quantity: 24 },
          { item: "Machine Parts", quantity: 14 },
        ],
        tech_requirements: ["tech-vehicle-fabrication"],
      },
    ],
    blueprints: [
      {
        id: "bp-wall-standard",
        label: "Standard Wall Segment",
        asset_type: "building",
        stats: { durability: 100, defense: 40, power: 0, capacity: 0, speed: 0, weight: 80 },
        resource_costs: [
          { item: "Wood", quantity: 50 },
          { item: "Metal", quantity: 20 },
        ],
        tech_requirements: ["tech-construction-basics"],
      },
      {
        id: "bp-wall-reinforced",
        label: "Reinforced Wall Segment",
        asset_type: "building",
        stats: { durability: 180, defense: 85, power: 0, capacity: 0, speed: 0, weight: 125 },
        resource_costs: [
          { item: "Metal", quantity: 90 },
          { item: "Concrete Mix", quantity: 40 },
          { item: "Tool Kit", quantity: 1 },
        ],
        tech_requirements: ["tech-materials-tier2", "tech-construction-basics"],
      },
      {
        id: "bp-scout-vehicle",
        label: "Scout Vehicle Package",
        asset_type: "vehicle",
        stats: { durability: 95, defense: 25, power: 18, capacity: 40, speed: 120, weight: 1300 },
        resource_costs: [
          { item: "Machine Parts", quantity: 40 },
          { item: "Rubber", quantity: 20 },
          { item: "Fuel Cell", quantity: 4 },
        ],
        tech_requirements: ["tech-vehicle-fabrication"],
      },
      {
        id: "bp-hauler-vehicle",
        label: "Hauler Vehicle Package",
        asset_type: "vehicle",
        stats: { durability: 130, defense: 30, power: 25, capacity: 120, speed: 85, weight: 2300 },
        resource_costs: [
          { item: "Machine Parts", quantity: 65 },
          { item: "Alloy Plate", quantity: 35 },
          { item: "Fuel Cell", quantity: 6 },
        ],
        tech_requirements: ["tech-vehicle-fabrication", "tech-logistics-expansion"],
      },
    ],
    tech_tree: [
      {
        id: "tech-construction-basics",
        label: "Construction Basics",
        tier: 1,
        requires: [],
        resource_costs: [
          { item: "Wood", quantity: 80 },
          { item: "Metal", quantity: 40 },
        ],
        unlocks: ["bp-wall-standard"],
      },
      {
        id: "tech-materials-tier2",
        label: "Tier-2 Materials",
        tier: 2,
        requires: ["tech-construction-basics"],
        resource_costs: [
          { item: "Concrete Mix", quantity: 60 },
          { item: "Alloy Plate", quantity: 25 },
        ],
        unlocks: ["bp-wall-reinforced", "mod-reinforced-plating"],
      },
      {
        id: "tech-grid-optimization",
        label: "Grid Optimization",
        tier: 2,
        requires: ["tech-construction-basics"],
        resource_costs: [
          { item: "Electronics", quantity: 45 },
          { item: "Copper Wire", quantity: 80 },
        ],
        unlocks: ["mod-efficient-grid-controller"],
      },
      {
        id: "tech-vehicle-fabrication",
        label: "Vehicle Fabrication",
        tier: 2,
        requires: ["tech-construction-basics"],
        resource_costs: [
          { item: "Machine Parts", quantity: 90 },
          { item: "Rubber", quantity: 50 },
          { item: "Fuel Cell", quantity: 10 },
        ],
        unlocks: ["bp-scout-vehicle", "mod-lightweight-chassis"],
      },
      {
        id: "tech-logistics-expansion",
        label: "Logistics Expansion",
        tier: 3,
        requires: ["tech-vehicle-fabrication", "tech-materials-tier2"],
        resource_costs: [
          { item: "Alloy Plate", quantity: 70 },
          { item: "Electronics", quantity: 30 },
          { item: "Fuel Cell", quantity: 12 },
        ],
        unlocks: ["bp-hauler-vehicle"],
      },
    ],
    research_state: [],
    defense_heatmap: {
      cols: 12,
      rows: 8,
      attack_decay_hours: 48,
      influence_radius: 20,
      red_threshold: 65,
      green_threshold: 35,
      attack_keywords: ["attack", "breach", "raid", "intrusion", "base hit"],
      sensor_alert_keywords: ["enemy", "hostile", "distress", "horde", "under fire"],
      sensor_threat_types: ["Enemy Sighting", "Horde Sighting", "Danger Zone"],
      severity_weights: {
        critical: 34,
        alert: 24,
        warn: 16,
        info: 8,
        default: 12,
      },
    },
    forecast_resources: [
      {
        id: "power",
        label: "Power",
        unit: "units",
        patterns: ["power cell", "battery", "fuel cell", "generator fuel"],
        base_burn_per_hour: 4,
        module_power_weight: 0.9,
        threat_weight: 0.6,
        activity_weight: 0.4,
      },
      {
        id: "fuel",
        label: "Fuel",
        unit: "liters",
        patterns: ["fuel", "diesel", "gasoline"],
        base_burn_per_hour: 3,
        module_power_weight: 0.7,
        threat_weight: 0.5,
        activity_weight: 0.5,
      },
      {
        id: "food",
        label: "Food",
        unit: "rations",
        patterns: ["food", "ration", "canned"],
        base_burn_per_hour: 2,
        module_power_weight: 0.1,
        threat_weight: 0.3,
        activity_weight: 0.9,
      },
      {
        id: "ammo",
        label: "Ammunition",
        unit: "rounds",
        patterns: ["ammo", "round", "shell"],
        base_burn_per_hour: 5,
        module_power_weight: 0.3,
        threat_weight: 1.2,
        activity_weight: 0.2,
      },
    ],
    consumption_scenarios: [
      { id: "normal", label: "Normal", activity_factor: 1, threat_factor: 1, environment_factor: 1 },
      { id: "high_activity", label: "High Activity", activity_factor: 1.35, threat_factor: 1.1, environment_factor: 1 },
      { id: "elevated_threat", label: "Elevated Threat", activity_factor: 1.1, threat_factor: 1.5, environment_factor: 1.05 },
      { id: "siege", label: "Siege", activity_factor: 1.4, threat_factor: 2.1, environment_factor: 1.15 },
    ],
    degradation: {
      critical_threshold: 35,
      baseline_decay_per_day: 2.4,
      attack_damage_decay_weight: 0.9,
      stale_module_penalty_per_day: 0.35,
      repair_time_hours_per_10_integrity: 0.8,
    },
  },
};
